comment: false
coverage:
  status:
    project:
      default:
        # basic
        target: 70
        threshold: 5
        base: auto 

coverage:
  status:
    patch:
      default:
        # basic
        target: 70
        threshold: 5
        base: auto 
