comment: false
coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 100
        base: auto 

coverage:
  status:
    patch:
      default:
        # basic
        target: 0
        threshold: 100
        base: auto 
